name: Terraform Deployment

on:
  push:
    branches:
      - master  # Runs on push to master branch
  pull_request:
    branches:
      - master  # Runs on PR to master branch

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Set your Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        id: fmt-check
        run: |
          terraform fmt -check || echo "formatting_needed=true" >> $GITHUB_ENV

      - name: Fix Terraform Formatting (if needed)
        if: env.formatting_needed == 'true'
        run: |
          terraform fmt -recursive
          echo "Terraform formatting fixed. Please commit the changes."

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Only on master branch)
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy (Manual Trigger)
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve
